In [13]:
import heapq

# Define a Node class to represent each node in the graph
class Node:
    def __init__(self, x, y, cost):
        self.x = x
        self.y = y
        self.cost = cost

    # Define the comparison operators for Node class to use with heapq
    def __lt__(self, other):
        return self.cost < other.cost

    def __eq__(self, other):
        return self.x == other.x and self.y == other.y and self.cost == other.cost

# Define the BFS algorithm
def bfs(graph, start, end):
    queue = [start]
    visited = set()
    while queue:
        node = queue.pop(0)
        if node == end:
            return node.cost
        for neighbor in get_neighbors(graph, node):
            if neighbor not in visited:
                queue.append(neighbor)
                visited.add(neighbor)

# Define the UCS algorithm
def ucs(graph, start, end):
    heap = [start]
    visited = set()
    while heap:
        node = heapq.heappop(heap)
        if node == end:
            return node.cost
        if node not in visited:
            visited.add(node)
            for neighbor in get_neighbors(graph, node):
                heapq.heappush(heap, neighbor)

# Define the A* algorithm
def astar(graph, start, end):
    heap = [start]
    visited = set()
    while heap:
        node = heapq.heappop(heap)
        if node == end:
            return node.cost
        if node not in visited:
            visited.add(node)
            for neighbor in get_neighbors(graph, node):
                # Calculate the heuristic cost (Manhattan distance)
                h_cost = abs(end.x - neighbor.x) + abs(end.y - neighbor.y)
                # Calculate the total cost
                total_cost = node.cost + neighbor.cost + h_cost
                heapq.heappush(heap, Node(neighbor.x, neighbor.y, total_cost))

# Get all the valid neighbors of a node
def get_neighbors(graph, node):
    neighbors = []
    for dx, dy in [(0, 1), (1, 0), (0, -1), (-1, 0)]:
        print('nodex',node.x)
        print('nodey:',node.y)
        x = node.x + dx
        y = node.y + dy
        print('dx,dy',dx,dy)
        print('x,y:',x,y)
        if 0 <= x < len(graph) and 0 <= y < len(graph[0]) and graph[x][y] != 'X':
            print('grapxy',graph[x][y])
            print('grapnodexy',graph[node.x][node.y])
            print('grapnodexy:',graph[1][1])
            print(graph[x][y].dtype)
            cost = abs(int(graph[x][y]) - int(graph[node.x][node.y])) + 1
            neighbors.append(Node(x, y, cost))
    return neighbors

# Read the input file
with open("input.txt", "r") as f:
    # Parse the dimensions and the start and end positions
    rows, cols = map(int, f.readline().split())
    start_x, start_y = map(int, f.readline().split())
    end_x, end_y = map(int, f.readline().split())

    # Parse the map
    graph = []
    for _ in range(rows):
        row = f.readline().strip()
        graph.append(row)
print(rows,cols)
print(start_x,start_y)
print(end_x,end_y)
print(graph)
# Run the algorithms and print the results
start = Node(start_x, start_y, 0)
end = Node(end_x, end_y, 0)
print("BFS:", bfs(graph, start, end))
print("UCS:", ucs(graph, start, end))
print("A*:", astar(graph, start, end))


10 10
1 1
10 10
['1 1 1 1 1 1 4 7 8 X', '1 1 1 1 1 1 1 5 8 8', '1 1 1 1 1 1 1 4 6 7', '1 1 1 1 1 X 1 1 3 6', '1 1 1 1 1 X 1 1 1 1', '1 1 1 1 1 1 1 1 1 1', '6 1 1 1 1 X 1 1 1 1', '7 7 1 X X X 1 1 1 1', '8 8 1 1 1 1 1 1 1 1', 'X 8 7 1 1 1 1 1 1 1']
nodex 1
nodey: 1
dx,dy 0 1
x,y: 1 2
grapxy 1
grapnodexy  
grapnodexy:  


AttributeError: 'str' object has no attribute 'dtype'

In [16]:
import queue

# read map data from file
with open("input.txt") as f:
    rows, cols = map(int, f.readline().split())
    start_row, start_col = map(int, f.readline().split())
    end_row, end_col = map(int, f.readline().split())
    map_data = []
    for i in range(rows):
        row_data = f.readline().strip().split()
        # convert 'X' to a large number
        row_data = [1000000 if cell == 'X' else int(cell) for cell in row_data]
        map_data.append(row_data)
print(map_data)
# BFS algorithm
q = queue.Queue()
q.put((start_row, start_col))
visited = set()
visited.add((start_row, start_col))
parents = {}
costs = {}
costs[(start_row, start_col)] = 0
while not q.empty():
    curr_row, curr_col = q.get()
    if curr_row == end_row and curr_col == end_col:
        break
    for dr, dc in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
        next_row, next_col = curr_row + dr, curr_col + dc
        if next_row >= 0 and next_row < rows and next_col >= 0 and next_col < cols and (next_row, next_col) not in visited and map_data[next_row][next_col] != "X":
            visited.add((next_row, next_col))
            q.put((next_row, next_col))
            parents[(next_row, next_col)] = (curr_row, curr_col)
            cost = 1 if map_data[curr_row][curr_col] == map_data[next_row][next_col] else 1 + abs(map_data[curr_row][curr_col] - map_data[next_row][next_col])
            costs[(next_row, next_col)] = costs[(curr_row, curr_col)] + cost

# print shortest path cost
print("Shortest path cost:", costs[(end_row, end_col)])

# print shortest path coordinates
path = []
curr_row, curr_col = end_row, end_col
while (curr_row, curr_col) != (start_row, start_col):
    path.append((curr_row, curr_col))
    curr_row, curr_col = parents[(curr_row, curr_col)]
path.append((start_row, start_col))
path.reverse()
print("Shortest path coordinates:", path)

# print path on the map
for row in range(rows):
    for col in range(cols):
        if (row, col) == (start_row, start_col):
            print("S", end="")
        elif (row, col) == (end_row, end_col):
            print("E", end="")
        elif (row, col) in path:
            print("*", end="")
        else:
            print(map_data[row][col], end="")
        print(" ", end="")
    print()


[[1, 1, 1, 1, 1, 1, 4, 7, 8, 1000000], [1, 1, 1, 1, 1, 1, 1, 5, 8, 8], [1, 1, 1, 1, 1, 1, 1, 4, 6, 7], [1, 1, 1, 1, 1, 1000000, 1, 1, 3, 6], [1, 1, 1, 1, 1, 1000000, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [6, 1, 1, 1, 1, 1000000, 1, 1, 1, 1], [7, 7, 1, 1000000, 1000000, 1000000, 1, 1, 1, 1], [8, 8, 1, 1, 1, 1, 1, 1, 1, 1], [1000000, 8, 7, 1, 1, 1, 1, 1, 1, 1]]


KeyError: (10, 10)

In [24]:
from collections import deque

# 读入地图信息
with open('input.txt', 'r') as f:
    rows, cols = map(int, f.readline().strip().split())
    start_row, start_col = map(int, f.readline().strip().split())
    end_row, end_col = map(int, f.readline().strip().split())
    matrix = []
    for i in range(rows):
        row = list(f.readline().strip())
        matrix.append(row)
print(matrix)
print(matrix[1][1])
# 计算两点之间的花费
def calc_cost(curr_row, curr_col, next_row, next_col):
    if matrix[curr_row][curr_col] == 'X' or matrix[next_row][next_col] == 'X':
        return float('inf')
    if curr_row == next_row and curr_col == next_col:
        return 0
    if matrix[curr_row][curr_col] == matrix[next_row][next_col]:
        return 1
    else:
        return 1 + abs(int(matrix[curr_row][curr_col]) - int(matrix[next_row][next_col]))

# 初始化起点
queue = deque([(start_row, start_col)])
visited = {(start_row, start_col): 0}
parent = {(start_row, start_col): None}

# BFS 搜索
while queue:
    curr_row, curr_col = queue.popleft()
    if curr_row == end_row and curr_col == end_col:
        break
    for next_row, next_col in [(curr_row-1, curr_col), (curr_row+1, curr_col), (curr_row, curr_col-1), (curr_row, curr_col+1)]:
        cost = calc_cost(curr_row, curr_col, next_row, next_col)
        if (next_row, next_col) not in visited or visited[(next_row, next_col)] > visited[(curr_row, curr_col)] + cost:
            visited[(next_row, next_col)] = visited[(curr_row, curr_col)] + cost
            parent[(next_row, next_col)] = (curr_row, curr_col)
            queue.append((next_row, next_col))

# 输出结果
with open('output.txt', 'w') as f:
    f.write(str(visited[(end_row, end_col)]) + '\n')
    path = []
    curr_row, curr_col = end_row, end_col
    while (curr_row, curr_col) != (start_row, start_col):
        path.append((curr_row, curr_col))
        curr_row, curr_col = parent[(curr_row, curr_col)]
    path.append((start_row, start_col))
    path.reverse()
    for i in range(rows):
        for j in range(cols):
            if (i, j) == (start_row, start_col) or (i, j) == (end_row, end_col):
                f.write('S' if (i, j) == (start_row, start_col) else 'E')
            elif (i, j) in path:
                f.write('*')
            else:
                f.write(matrix[i][j])
        f.write('\n')


[['1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '4', ' ', '7', ' ', '8', ' ', 'X'], ['1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '5', ' ', '8', ' ', '8'], ['1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '4', ' ', '6', ' ', '7'], ['1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', 'X', ' ', '1', ' ', '1', ' ', '3', ' ', '6'], ['1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', 'X', ' ', '1', ' ', '1', ' ', '1', ' ', '1'], ['1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1'], ['6', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', 'X', ' ', '1', ' ', '1', ' ', '1', ' ', '1'], ['7', ' ', '7', ' ', '1', ' ', 'X', ' ', 'X', ' ', 'X', ' ', '1', ' ', '1', ' ', '1', ' ', '1'], ['8', ' ', '8', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1'], ['X', ' ', '8', ' ', '7', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1', ' ', '1']]
 


ValueError: invalid literal for int() with base 10: ' '

In [ ]:
import numpy as np
from queue import Queue

# 读取文本文件
with open("map.txt", "r") as f:
    # 读取地图行数和列数
    rows, cols = map(int, f.readline().split())
    # 读取起点和终点坐标
    sx, sy = map(int, f.readline().split())
    ex, ey = map(int, f.readline().split())
    # 读取地图数据并转换为numpy矩阵
    data = np.zeros((rows, cols))
    for i in range(rows):
        line = f.readline().strip()
        for j in range(cols):
            if line[j] == "X":
                data[i, j] = -1
            else:
                data[i, j] = int(line[j])

# 定义BFS算法
def bfs(sx, sy, ex, ey, data):
    # 定义队列和访问数组
    q = Queue()
    visited = np.zeros((rows, cols))
    # 定义步长数组和路径数组
    dx = [-1, 0, 1, 0]
    dy = [0, 1, 0, -1]
    path = np.zeros((rows, cols))

    # 将起点入队，并标记为已访问
    q.put((sx, sy))
    visited[sx, sy] = 1

    # 开始BFS搜索
    while not q.empty():
        # 取出队列中的头部节点
        x, y = q.get()
        # 如果到达终点，退出搜索
        if x == ex and y == ey:
            break
        # 遍历当前节点的四个相邻节点
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            # 如果相邻节点在地图内且未被访问过
            if nx >= 0 and nx < rows and ny >= 0 and ny < cols and visited[nx, ny] == 0 and data[nx, ny] != -1:
                # 标记相邻节点为已访问
                visited[nx, ny] = 1
                # 计算到达相邻节点的cost
                if data[x, y] == data[nx, ny]:
                    cost = 1
                else:
                    cost = 1 + abs(data[x, y] - data[nx, ny])
                # 更新到达相邻节点的路径数组和cost
                path[nx, ny] = path[x, y] + cost
                # 将相邻节点入队
                q.put((nx, ny))

    # 输出最短路径的cost和坐标
    print("最短路径的cost为：", path[ex, ey])
    print("最短路径的坐标为：")
    x, y = ex, ey
    while x != sx or y != sy:
        print(x, y)
        minx, miny, minpath = x, y, path[x, y]
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            if nx >= 0 and nx < rows and ny >= 0 and ny < cols and path[nx, ny] < minpath:
                minx, miny, minpath = nx, ny, path[nx, ny]
        x, y = minx, miny
        # 生成最短路径的二维矩阵
    shortest_path = np.zeros((rows, cols))
    x, y = ex, ey
    while x != sx or y != sy:
        shortest_path[x, y] = 1
        minx, miny, minpath = x, y, path[x, y]
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            if nx >= 0 and nx < rows and ny >= 0 and ny < cols and path[nx, ny] < minpath:
                minx, miny, minpath = nx, ny, path[nx, ny]
        x, y = minx, miny
    shortest_path[sx, sy] = 1

    # 输出最短路径的二维矩阵
    print("最短路径的二维矩阵为：")
    for i in range(rows):
        for j in range(cols):
            if shortest_path[i, j] == 1:
                print("*", end="")
            else:
                if data[i, j] == -1:
                    print("X", end="")
                else:
                    print(int(data[i, j]), end="")
        print()


In [2]:
import numpy as np
import queue

# 定义一个类来表示每个节点
class Node:
    def __init__(self, x, y, cost):
        self.x = x
        self.y = y
        self.cost = cost

# 定义BFS算法
def BFS(matrix, start, end):
    m, n = matrix.shape
    visited = np.zeros((m, n))
    q = queue.Queue()
    q.put(Node(start[0]-1, start[1]-1, 0))
    
    dx = [-1, 0, 1, 0]
    dy = [0, 1, 0, -1]

    while not q.empty():
        cur = q.get()
        print('x,y:',cur.x,cur.y)
        if cur.x == end[0]-1 and cur.y == end[1]-1:
            return cur.cost

        for i in range(4):
            nx = cur.x + dx[i]
            ny = cur.y + dy[i]
            if nx < 0 or nx >= m or ny < 0 or ny >= n:
                continue
            if visited[nx][ny] == 1 or matrix[nx][ny] == "X":
                continue

            if matrix[nx][ny] == matrix[cur.x][cur.y]:
                cost = 1
            else:
                cost = 1 + abs(int(matrix[nx][ny]) - int(matrix[cur.x][cur.y]))

            q.put(Node(nx, ny, cur.cost + cost))
            visited[nx][ny] = 1
    return -1


# 读取文件中的地图信息
with open("input.txt", "r") as f:
    line = f.readline().strip()
    m, n = map(int, line.split())

    line = f.readline().strip()
    start = tuple(map(int, line.split()))
    print(start)
    line = f.readline().strip()
    end = tuple(map(int, line.split()))

    matrix = []
    for i in range(m):
        line = f.readline().strip().split()
        matrix.append(line)

# 将地图信息转化为二维矩阵
matrix = np.array(matrix)
print(matrix)
# 进行BFS算法搜索
cost = BFS(matrix, start, end)
print("最短路径的cost为：", cost)

# 输出最短路径坐标
if cost != -1:
    dx = [-1, 0, 1, 0]
    dy = [0, 1, 0, -1]
    cur = Node(end[0]-1, end[1]-1, 0)
    path = [(cur.x, cur.y)]
    print('curx,cury:',cur.x,cur.y)

    while cur.x != start[0]-1 and cur.y != start[1]-1:
        for i in range(4):
            nx = cur.x + dx[i]
            ny = cur.y + dy[i]
            print('nx,ny:',nx,ny)
            #判断坐标有无越界
            if nx < 0 or nx >= m-1 or ny < 0 or ny >= n-1:
                continue
            print(visited[nx][ny])
            if visited[nx][ny] == 0:
                continue

            if matrix[nx][ny] == matrix[cur.x][cur.y]:
                cost = 1
            else:
                cost = 1 + abs(int(matrix[nx][ny]) - int(matrix[cur.x][cur.y]))

            if cur.cost - cost == visited[nx][ny]:
                cur = Node(nx, ny, visited[nx][ny])
                path.append((cur.x, cur.y))
                print(path)
                break

    path.reverse()
    print("最短路径坐标为：", path)

# 输出最短路径的地图
if cost != -1:
    for i in range(m):
        for j in range(n):
            if (i,j) in path:
                print('*',end='')
            else:
                print(matrix[i][j],end="")
                print()



(1, 1)
[['1' '1' '1' '1' '1' '1' '4' '7' '8' 'X']
 ['1' '1' '1' '1' '1' '1' '1' '5' '8' '8']
 ['1' '1' '1' '1' '1' '1' '1' '4' '6' '7']
 ['1' '1' '1' '1' '1' 'X' '1' '1' '3' '6']
 ['1' '1' '1' '1' '1' 'X' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['6' '1' '1' '1' '1' 'X' '1' '1' '1' '1']
 ['7' '7' '1' 'X' 'X' 'X' '1' '1' '1' '1']
 ['8' '8' '1' '1' '1' '1' '1' '1' '1' '1']
 ['X' '8' '7' '1' '1' '1' '1' '1' '1' '1']]
x,y: 0 0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
x,y: 0 1
[[1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0

In [23]:
import numpy as np
from queue import Queue

# 读取地图信息
with open("input.txt") as f:
    # 读取行数和列数
    rows, cols = map(int, f.readline().strip().split())
    # 读取起点坐标和终点坐标
    start_row, start_col = map(int, f.readline().strip().split())
    end_row, end_col = map(int, f.readline().strip().split())
    # 读取地图数据
    matrix = []
    for i in range(rows):
        line = f.readline().strip().split()
        matrix.append(line)

# 将地图信息转化为二维矩阵
matrix = np.array(matrix)
print(matrix)
# 将地图信息转换为二维矩阵
map_matrix = np.zeros((rows, cols))
for i in range(rows):
    for j in range(cols):
        if matrix[i][j] == "X":
            map_matrix[i][j] = -1
        else:
            map_matrix[i][j] = int(matrix[i][j])
print(map_matrix)
# 定义 BFS 算法
def bfs(start, end, matrix):
    queue = Queue()
    queue.put(start)
    visited = set()
    visited.add(start)
    parents = {}
    while not queue.empty():
        node = queue.get()
        if node == end:
            break
        neighbors = []
        row, col = node
        # 获取上下左右四个邻居
        if row > 0 and matrix[row-1][col] != -1:
            neighbors.append((row-1, col))
        if row < matrix.shape[0]-1 and matrix[row+1][col] != -1:
            neighbors.append((row+1, col))
        if col > 0 and matrix[row][col-1] != -1:
            neighbors.append((row, col-1))
        if col < matrix.shape[1]-1 and matrix[row][col+1] != -1:
            neighbors.append((row, col+1))
        for neighbor in neighbors:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.put(neighbor)
                parents[neighbor] = node

    # 从终点开始回溯路径
    path = []
    cost = 0
    node = end
    while node != start:
        path.append(node)
        parent = parents[node]
        cost += get_cost(node, parent, matrix)
        node = parent
    path.append(start)
    path.reverse()

    return path, cost

# 计算两个节点之间的成本
def get_cost(node1, node2, matrix):
    if matrix[node1[0]][node1[1]] == matrix[node2[0]][node2[1]]:
        return 1
    else:
        return 1 + abs(matrix[node1[0]][node1[1]] - matrix[node2[0]][node2[1]])

# 执行 BFS 算法
start = (start_row-1, start_col-1)
end = (end_row-1, end_col-1)
path, cost = bfs(start, end, map_matrix)

out_mat = matrix

for i in range(0,len(path)):
    mod_row = path[i][0]
    mod_col = path[i][1]
    out_mat[mod_row][mod_col] = '*'
print(out_mat)

if len(path) == 0:
    print("null")
else:
    with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
        while not it.finished:
            row, col = it.multi_index
            if col == 0:
                print()  # 换行
            print(matrix[row][col], end=' ')
            it.iternext()


[['1' '1' '1' '1' '1' '1' '4' '7' '8' 'X']
 ['1' '1' '1' '1' '1' '1' '1' '5' '8' '8']
 ['1' '1' '1' '1' '1' '1' '1' '4' '6' '7']
 ['1' '1' '1' '1' '1' 'X' '1' '1' '3' '6']
 ['1' '1' '1' '1' '1' 'X' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['6' '1' '1' '1' '1' 'X' '1' '1' '1' '1']
 ['7' '7' '1' 'X' 'X' 'X' '1' '1' '1' '1']
 ['8' '8' '1' '1' '1' '1' '1' '1' '1' '1']
 ['X' '8' '7' '1' '1' '1' '1' '1' '1' '1']]
[[ 1.  1.  1.  1.  1.  1.  4.  7.  8. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  5.  8.  8.]
 [ 1.  1.  1.  1.  1.  1.  1.  4.  6.  7.]
 [ 1.  1.  1.  1.  1. -1.  1.  1.  3.  6.]
 [ 1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 6.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
 [ 7.  7.  1. -1. -1. -1.  1.  1.  1.  1.]
 [ 8.  8.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1.  8.  7.  1.  1.  1.  1.  1.  1.  1.]]
[['*' '1' '1' '1' '1' '1' '4' '7' '8' 'X']
 ['*' '1' '1' '1' '1' '1' '1' '5' '8' '8']
 ['*' '1' '1' '1' '1' '1' '1' '4' '6' '7']
 ['*' '1'

In [30]:
import numpy as np
import heapq
import sys
# 读取文件并初始化地图
def initialize_map(file_path):
    with open(file_path, 'r') as f:
        rows, cols = map(int, f.readline().split())
        start_row, start_col = map(int, f.readline().split())
        end_row, end_col = map(int, f.readline().split())
        map_data = []
        for i in range(rows):
            row_data = f.readline().split()
            map_data.append(row_data)
    matrix = np.array(map_data)
    map_matrix = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == "X":
                map_matrix[i][j] = -1
            else:
                map_matrix[i][j] = int(matrix[i][j])
    return matrix,map_matrix, (start_row-1, start_col-1), (end_row-1, end_col-1)

# 计算两点间的花费
def get_cost(map_data, curr_pos, next_pos):
    curr_alt = int(map_data[curr_pos])
    next_alt = int(map_data[next_pos])
    if curr_alt == next_alt:
        return 1
    else:
        return 1 + abs(curr_alt - next_alt)

# 判断一个位置是否可行
def is_valid_pos(map_data, pos):
    if pos[0] < 0 or pos[0] >= map_data.shape[0]:
        return False
    if pos[1] < 0 or pos[1] >= map_data.shape[1]:
        return False
    if map_data[pos] == 'X':
        return False
    return True

def bfs(map_data,start, end):
    matrix = map_data
    queue = Queue()
    queue.put(start)
    visited = set()
    visited.add(start)
    parents = {}
    while not queue.empty():
        node = queue.get()
        if node == end:
            break
        neighbors = []
        row, col = node
        # 获取上下左右四个邻居
        if row > 0 and matrix[row-1][col] != -1:
            neighbors.append((row-1, col))
        if row < matrix.shape[0]-1 and matrix[row+1][col] != -1:
            neighbors.append((row+1, col))
        if col > 0 and matrix[row][col-1] != -1:
            neighbors.append((row, col-1))
        if col < matrix.shape[1]-1 and matrix[row][col+1] != -1:
            neighbors.append((row, col+1))
        for neighbor in neighbors:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.put(neighbor)
                parents[neighbor] = node

    # 从终点开始回溯路径
    path = []
    cost = 0
    node = end
    while node != start:
        path.append(node)
        parent = parents[node]
        cost += get_cost(node, parent, matrix)
        node = parent
    path.append(start)
    path.reverse()

    return path
# 寻找从起点到终点的最短路径
def ucs_search(map_data, start_pos, end_pos):
    visited = set()
    queue = [(0, start_pos, [])]
    heapq.heapify(queue)
    while queue:
        curr_cost, curr_pos, path = heapq.heappop(queue)
        if curr_pos in visited:
            continue
        visited.add(curr_pos)
        path = path + [curr_pos]
        if curr_pos == end_pos:
            return path
        for i, j in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            next_pos = (curr_pos[0] + i, curr_pos[1] + j)
            if is_valid_pos(map_data, next_pos):
                next_cost = curr_cost + get_cost(map_data, curr_pos, next_pos)
                heapq.heappush(queue, (next_cost, next_pos, path))
    return None

# 主函数
def run_findpath(matrix,map_data, start_pos, end_pos):
    
    shortest_path = ucs_search(map_data, start_pos, end_pos)
    out_mat = matrix

    for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
    print(out_mat)
    if shortest_path:
        print("最短路径为：", shortest_path)
        with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
            while not it.finished:
                row, col = it.multi_index
                if col == 0:
                    print()  # 换行
                print(matrix[row][col], end=' ')
                it.iternext()
    else:
        print("null")

if __name__ == '__main__':
    file_path = sys.argv[1]
    algorithm = sys.argv[2]
    options = sys.argv[3:]
    ori_matrix,map_data, start_pos, end_pos = initialize_map(file_path)
    if algorithm == 'BFS':
        path = bfs(ori_matrix,map_data, start_pos, end_pos)
    elif algorithm == 'UCS':
        path = ucs_search(map_data, start_pos, end_pos)


    out_mat = matrix
    for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
    print(out_mat)
    if path:
        print("最短路径为：", path)
        with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
            while not it.finished:
                row, col = it.multi_index
                if col == 0:
                    print()  # 换行
                print(matrix[row][col], end=' ')
                it.iternext()
    else:
        print("null")
    # elif algorithm == 'A*':
    #     if options[0] == 'euclidean':
    #         heuristic_func = euclidean_distance
    #     else:
    #         heuristic_func = manhattan_distance

[['*' '1' '1' '1' '1' '1' '4' '7' '8' 'X']
 ['*' '1' '1' '1' '1' '1' '1' '5' '8' '8']
 ['*' '1' '1' '1' '1' '1' '1' '4' '6' '7']
 ['*' '1' '1' '1' '1' 'X' '1' '1' '3' '6']
 ['*' '1' '1' '1' '1' 'X' '1' '1' '1' '1']
 ['*' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['*' '1' '1' '1' '1' 'X' '1' '1' '1' '1']
 ['*' '7' '1' 'X' 'X' 'X' '1' '1' '1' '1']
 ['*' '*' '1' '1' '1' '1' '1' '1' '1' '1']
 ['X' '*' '*' '*' '*' '*' '*' '*' '*' '*']]
最短路径为： [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 5), (1, 6), (2, 6), (3, 6), (3, 7), (4, 7), (4, 8), (4, 9), (5, 9), (6, 9), (7, 9), (8, 9), (9, 9)]

* 1 1 1 1 1 4 7 8 X 
* 1 1 1 1 1 1 5 8 8 
* 1 1 1 1 1 1 4 6 7 
* 1 1 1 1 X 1 1 3 6 
* 1 1 1 1 X 1 1 1 1 
* 1 1 1 1 1 1 1 1 1 
* 1 1 1 1 X 1 1 1 1 
* 7 1 X X X 1 1 1 1 
* * 1 1 1 1 1 1 1 1 
X * * * * * * * * * 

In [5]:
#A*算法
def initialize_map(file_path):
    with open(file_path, 'r') as f:
        rows, cols = map(int, f.readline().split())
        start_row, start_col = map(int, f.readline().split())
        end_row, end_col = map(int, f.readline().split())
        map_data = []
        for i in range(rows):
            row_data = f.readline().split()
            map_data.append(row_data)
    matrix = np.array(map_data)
    map_matrix = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == "X":
                map_matrix[i][j] = -1
            else:
                map_matrix[i][j] = int(matrix[i][j])
    return matrix,map_matrix, (start_row-1, start_col-1), (end_row-1, end_col-1)

import numpy as np
import heapq

def get_neighbors(node, grid):
    """返回节点周围可到达的邻居"""
    neighbors = []
    rows, cols = grid.shape
    row, col = node
    
    # 上方邻居
    if row > 0 and grid[row-1, col] != 'X':
        neighbors.append((row-1, col))
    
    # 下方邻居
    if row < rows-1 and grid[row+1, col] != 'X':
        neighbors.append((row+1, col))
    
    # 左侧邻居
    if col > 0 and grid[row, col-1] != 'X':
        neighbors.append((row, col-1))
    
    # 右侧邻居
    if col < cols-1 and grid[row, col+1] != 'X':
        neighbors.append((row, col+1))
    
    return neighbors

def get_cost_astar(node1, node2, grid):
    """返回节点之间的代价"""
    elev1 = int(grid[node1])
    elev2 = int(grid[node2])
    if elev1 == elev2:
        return 1
    else:
        return 1 + abs(elev1 - elev2)

def heuristic(node, goal_node, heuristic_type):
    """返回节点到目标节点的启发式距离"""
    if heuristic_type == 'euclidean':
        return np.linalg.norm(np.array(node) - np.array(goal_node))
    elif heuristic_type == 'manhattan':
        return abs(node[0] - goal_node[0]) + abs(node[1] - goal_node[1])
    else:
        raise ValueError('Invalid heuristic type')

def a_star(start_node, goal_node, grid, heuristic_type):
    """使用A*算法寻找从起点到终点的最短路径"""
    rows, cols = grid.shape
    
    # 创建空的距离和父节点字典
    distance = {}
    parent = {}
    for row in range(rows):
        for col in range(cols):
            distance[(row, col)] = float('inf')
            parent[(row, col)] = None
    
    # 初始化起点距离为0
    distance[start_node] = 0
    
    # 创建一个优先队列来存储节点
    queue = [(0, start_node)]
    
    # A*主循环
    while queue:
        # 取出距离最小的节点
        current_distance, current_node = heapq.heappop(queue)
        
        # 如果当前节点为目标节点，则返回路径
        if current_node == goal_node:
            path = []
            while current_node is not None:
                path.append(current_node)
                current_node = parent[current_node]
            path.reverse()
            return path
        
        # 获取当前节点周围的邻居
        neighbors = get_neighbors(current_node, grid)
        
        # 更新邻居节点的距离和父节点
        for neighbor in neighbors:
            cost = get_cost_astar(current_node, neighbor, grid)
            new_distance = distance[current_node] + cost + heuristic(neighbor, goal_node, heuristic_type)
            if new_distance < distance[neighbor]:
                distance[neighbor] = new_distance
                parent[neighbor] = current_node
                heapq.heappush(queue, (new_distance, neighbor))
    return []


ori_matrix,map_data, start_pos, end_pos = initialize_map('./input.txt')
path = a_star(start_pos,end_pos,map_data,'manhattan')
out_mat = ori_matrix

if path:
    for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
    with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
        while not it.finished:
            row, col = it.multi_index
            if col == 0:
                print()  # 换行
            print(ori_matrix[row][col], end=' ')
            it.iternext()
else:
    print("null")



* * * * * * 4 7 8 X 
1 1 1 1 1 * * 5 8 8 
1 1 1 1 1 1 * 4 6 7 
1 1 1 1 1 X * * 3 6 
1 1 1 1 1 X 1 * * * 
1 1 1 1 1 1 1 1 1 * 
6 1 1 1 1 X 1 1 1 * 
7 7 1 X X X 1 1 1 * 
8 8 1 1 1 1 1 1 1 * 
X 8 7 1 1 1 1 1 1 * 

In [4]:
import numpy as np
from queue import Queue

# 读取输入文件并创建numpy数组
with open("input.txt", "r") as f:
    rows, cols = map(int, f.readline().split())
    start_row, start_col = map(int, f.readline().split())
    end_row, end_col = map(int, f.readline().split())
    data = [[int(x) if x != "X" else np.inf for x in line.split()] for line in f.readlines()]
    data = np.array(data)

# 实现BFS算法
def bfs(data, start, end):
    visited = set()
    q = Queue()
    q.put((start, 0, [start]))
    while not q.empty():
        node, length, path = q.get()
        if node == end:
            return length, path
        visited.add(node)
        row, col = node
        neighbors = [(row-1, col), (row+1, col), (row, col-1), (row, col+1)]
        for r, c in neighbors:
            if r < 0 or r >= data.shape[0] or c < 0 or c >= data.shape[1] or (r,c) in visited or np.isinf(data[r,c]):
                continue
            cost = 1 + abs(data[r,c] - data[row,col])
            q.put(((r,c), length+cost, path+[(r,c)]))
            visited.add((r,c))
    return np.inf, []

# 使用BFS算法计算最短路径
start = (start_row-1, start_col-1)
end = (end_row-1, end_col-1)
length, path = bfs(data, start, end)

# 打印最短路径
if length == np.inf:
    print("No path found")
else:
    print("Shortest path length:", length)
    print("Shortest path coordinates:")
    for r, c in path:
        print(r, c)


Shortest path length: 32.0
Shortest path coordinates:
0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
8 1
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9


In [16]:
import numpy as np
import heapq

# 读入地图数据并转换成NumPy数组
import numpy as np

# 读取输入
with open("input1.txt", "r") as f:
    # 读取行数和列数
    n, m = map(int, f.readline().split())
    # 读取起点和终点坐标
    start_x, start_y = map(int, f.readline().split())
    end_x, end_y = map(int, f.readline().split())

    # 初始化地图矩阵
    map_matrix = np.zeros((n, m), dtype=int)

    # 读取地图信息并填充到矩阵中
    for i in range(n):
        line = f.readline().split()
        # 如果读取到的行数和声明的行数不匹配，则抛出异常
        if len(line) != m:
            raise ValueError("The number of columns does not match.")
        for j in range(m):
            if line[j] == "X":
                map_matrix[i][j] = -1  # 障碍物用-1表示
            else:
                map_matrix[i][j] = int(line[j])

# 定义UCS算法函数
def ucs(map_data, start_pos, end_pos):
    n_row, n_col = map_data.shape
    cost = np.zeros((n_row, n_col)) + np.inf  # 从起点到每个点的最小代价
    visited = np.zeros((n_row, n_col), dtype=bool)  # 标记每个点是否已访问
    parent = np.zeros((n_row, n_col, 2), dtype=int)  # 记录每个点的前继节点坐标

    cost[start_pos] = 0
    heap = [(0, start_pos)]

    while heap:
        _, curr_pos = heapq.heappop(heap)
        if curr_pos == end_pos:
            break
        visited[curr_pos] = True
        for drow, dcol in [(1, 0), (0, 1), (-1, 0), (0, -1)]:
            next_pos = (curr_pos[0]+drow, curr_pos[1]+dcol)
            if 0 <= next_pos[0] < n_row and 0 <= next_pos[1] < n_col and not visited[next_pos]:
                if map_data[next_pos] != 'X':
                    diff_height = abs(int(map_data[curr_pos])-int(map_data[next_pos]))
                    if diff_height == 0:
                        step_cost = 1
                    else:
                        step_cost = 1 + diff_height
                    new_cost = cost[curr_pos] + step_cost
                    if new_cost < cost[next_pos]:
                        cost[next_pos] = new_cost
                        parent[next_pos] = curr_pos
                        heapq.heappush(heap, (new_cost, next_pos))

    # 从终点向起点遍历，记录路径坐标
    path = []
    curr_pos = end_pos
    while curr_pos != start_pos:
        path.append(curr_pos)
        curr_pos = tuple(parent[curr_pos])
    path.append(start_pos)
    path.reverse()

    return path
start_pos = (start_x-1,start_y-1)
end_pos = (end_x-1,end_y-1)
# 运行UCS算法并标记路径
path = ucs(map_matrix, start_pos, end_pos)
for pos in path:
    map_data[pos] = '*'

# 输出结果
print(map_data)


[['*' '*' '*' '*' '*' '*' '4' '7' '8' 'X']
 ['1' '1' '1' '1' '1' '*' '*' '5' '8' '8']
 ['1' '1' '1' '1' '1' '1' '*' '4' '6' '7']
 ['1' '1' '1' '1' '1' 'X' '*' '*' '*' '6']
 ['1' '1' '1' '1' '1' 'X' '1' '*' '*' '*']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '*']
 ['6' '1' '1' '1' '1' 'X' '1' '1' '1' '*']
 ['7' '7' '1' 'X' 'X' 'X' '1' '1' '1' '*']
 ['8' '8' '1' '1' '1' '1' '1' '1' '1' '*']
 ['X' '8' '7' '1' '1' '1' '1' '1' '1' '*']]


In [26]:
import numpy as np
import heapq


# 读入地图数据并转换成NumPy数组
with open("input.txt", "r") as f:
    # 读取行数和列数
    n, m = map(int, f.readline().split())
    # 读取起点和终点坐标
    start_x, start_y = map(int, f.readline().split())
    end_x, end_y = map(int, f.readline().split())

    # 初始化地图矩阵
    map_matrix = np.zeros((n, m), dtype=int)

    # 读取地图信息并填充到矩阵中
    for i in range(n):
        line = f.readline().split()
        # 如果读取到的行数和声明的行数不匹配，则抛出异常
        if len(line) != m:
            raise ValueError("The number of columns does not match.")
        for j in range(m):
            if line[j] == "X":
                map_matrix[i, j] = -1  # 障碍物用-1表示
            else:
                map_matrix[i, j] = int(line[j])

# 定义UCS算法函数
def ucs(map_data, start_pos, end_pos):
    n_row, n_col = map_data.shape
    cost = np.full((n_row, n_col), np.inf)  # 从起点到每个点的最小代价
    visited = np.zeros((n_row, n_col), dtype=bool)  # 标记每个点是否已访问
    parent = np.zeros((n_row, n_col, 2), dtype=int)  # 记录每个点的前继节点坐标

    cost[start_pos] = 0
    heap = [(0, start_pos)]

    while heap:
        _, curr_pos = heapq.heappop(heap)
        if curr_pos == end_pos:
            break
        visited[curr_pos] = True
        for drow, dcol in [(1, 0), (0, 1), (-1, 0), (0, -1)]:
            next_pos = (curr_pos[0]+drow, curr_pos[1]+dcol)
            if 0 <= next_pos[0] < n_row and 0 <= next_pos[1] < n_col and not visited[next_pos]:
                next_height = map_data[next_pos]
                if next_height != -1:
                    curr_height = map_data[curr_pos]
                    step_cost = 1 + abs(curr_height - next_height) if curr_height != next_height else 1
                    new_cost = cost[curr_pos] + step_cost
                    if new_cost < cost[next_pos]:
                        cost[next_pos] = new_cost
                        parent[next_pos] = curr_pos
                        heapq.heappush(heap, (new_cost, next_pos))

    # 从终点向起点遍历，记录路径坐标
    path = []
    curr_pos = end_pos
    while curr_pos != start_pos:
        path.append(curr_pos)
        curr_pos = tuple(parent[curr_pos])
    path.append(start_pos)
    path.reverse()

    return path


start_pos = (start_x-1, start_y-1)
end_pos = (end_x-1, end_y-1)
# 运行UCS算法并标记路径
path = ucs(map_matrix, start_pos, end_pos)
# map_data =
print(path)
print(map_matrix)
out_mat = np.zeros((n, m), dtype=str)
for k in range(0,n):
    for j in range(0,m):
        if map_matrix[k][j] == -1:
            out_mat[k][j] = 'X'
        else:
            out_mat[k][j] = str(map_matrix[k][j])
        
for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
if path:
    with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
        while not it.finished:
            row, col = it.multi_index
            print(out_mat[row][col], end=' ')
            if col == cols-1:
                print()  # 换行
            
            it.iternext()
            
            
else:
    print("null")

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 5), (1, 6), (2, 6), (3, 6), (3, 7), (4, 7), (4, 8), (4, 9), (5, 9), (6, 9), (7, 9), (8, 9), (9, 9)]
[[ 1  1  1  1  1  1  4  7  8 -1]
 [ 1  1  1  1  1  1  1  5  8  8]
 [ 1  1  1  1  1  1  1  4  6  7]
 [ 1  1  1  1  1 -1  1  1  3  6]
 [ 1  1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 6  1  1  1  1 -1  1  1  1  1]
 [ 7  7  1 -1 -1 -1  1  1  1  1]
 [ 8  8  1  1  1  1  1  1  1  1]
 [-1  8  7  1  1  1  1  1  1  1]]
* * * * * * 4 7 8 X 
1 1 1 1 1 * * 5 8 8 
1 1 1 1 1 1 * 4 6 7 
1 1 1 1 1 X * * 3 6 
1 1 1 1 1 X 1 * * * 
1 1 1 1 1 1 1 1 1 * 
6 1 1 1 1 X 1 1 1 * 
7 7 1 X X X 1 1 1 * 
8 8 1 1 1 1 1 1 1 * 
X 8 7 1 1 1 1 1 1 * 


In [30]:
import numpy as np
import heapq

# 读取输入
with open("input1.txt", "r") as f:
    # 读取行数和列数
    n, m = map(int, f.readline().split())
    # 读取起点和终点坐标
    start_x, start_y = map(int, f.readline().split())
    end_x, end_y = map(int, f.readline().split())

    # 初始化地图矩阵
    map_matrix = np.zeros((n, m), dtype=int)

    # 读取地图信息并填充到矩阵中
    for i in range(n):
        line = f.readline().split()
        # 如果读取到的行数和声明的行数不匹配，则抛出异常
        if len(line) != m:
            raise ValueError("The number of columns does not match.")
        for j in range(m):
            if line[j] == "X":
                map_matrix[i][j] = -1  # 障碍物用-1表示
            else:
                map_matrix[i][j] = int(line[j])

# 定义UCS算法函数
def ucs(map_data, start_pos, end_pos):
    n_row, n_col = map_data.shape
    cost = np.zeros((n_row, n_col)) + np.inf  # 从起点到每个点的最小代价
    visited = np.zeros((n_row, n_col), dtype=bool)  # 标记每个点是否已访问
    parent = np.zeros((n_row, n_col, 2), dtype=int)  # 记录每个点的前继节点坐标

    cost[start_pos] = 0
    heap = [(0, start_pos)]

    while heap:
        _, curr_pos = heapq.heappop(heap)
        if curr_pos == end_pos:
            break
        visited[curr_pos] = True
        for drow, dcol in [(1, 0), (0, 1), (-1, 0), (0, -1)]:
            next_pos = (curr_pos[0]+drow, curr_pos[1]+dcol)
            if 0 <= next_pos[0] < n_row and 0 <= next_pos[1] < n_col and not visited[next_pos]:
                if map_data[next_pos] != -1:
                    diff_height = abs(int(map_data[curr_pos])-int(map_data[next_pos]))
                    if diff_height == 0:
                        step_cost = 1
                    else:
                        step_cost = 1 + diff_height
                    new_cost = cost[curr_pos] + step_cost
                    if new_cost < cost[next_pos]:
                        cost[next_pos] = new_cost
                        parent[next_pos] = curr_pos
                        heapq.heappush(heap, (new_cost, next_pos))

    # 从终点向起点遍历，记录路径坐标
    path = []
    curr_pos = end_pos
    while curr_pos != start_pos:
        path.append(curr_pos)
        curr_pos = tuple(parent[curr_pos])
    path.append(start_pos)
    print(path)
start_pos = (start_x-1,start_y-1)
end_pos = (end_x-1,end_y-1)
ucs(map_matrix,start_pos,end_pos)
out_mat = np.zeros((n, m), dtype=str)
for k in range(0,n):
    for j in range(0,m):
        if map_matrix[k][j] == -1:
            out_mat[k][j] = 'X'
        else:
            out_mat[k][j] = str(map_matrix[k][j])
        
for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
if path:
    with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
        while not it.finished:
            row, col = it.multi_index
            print(out_mat[row][col], end=' ')
            if col == cols-1:
                print()  # 换行
            
            it.iternext()
            
            
else:
    print("null")

[(9, 9), (8, 9), (7, 9), (6, 9), (5, 9), (4, 9), (4, 8), (3, 8), (3, 7), (3, 6), (2, 6), (1, 6), (1, 5), (0, 5), (0, 4), (0, 3), (0, 2), (0, 1), (0, 0)]
* * * * * * 4 7 8 X 
1 1 1 1 1 * * 5 8 8 
1 1 1 1 1 1 * 4 6 7 
1 1 1 1 1 X * * 1 6 
1 1 1 1 1 X 1 * * * 
1 1 1 1 1 1 1 1 1 * 
6 1 1 1 1 X 1 1 1 * 
7 7 1 X X X 1 1 1 * 
8 8 1 1 1 1 1 1 1 * 
X 8 7 1 1 1 1 1 1 * 


In [31]:
import numpy as np
import heapq

# 读取输入
with open("input1.txt", "r") as f:
    # 读取行数和列数
    n, m = map(int, f.readline().split())
    # 读取起点和终点坐标
    start_x, start_y = map(int, f.readline().split())
    end_x, end_y = map(int, f.readline().split())

    # 初始化地图矩阵
    map_matrix = np.zeros((n, m), dtype=int)

    # 读取地图信息并填充到矩阵中
    for i in range(n):
        line = f.readline().split()
        # 如果读取到的行数和声明的行数不匹配，则抛出异常
        if len(line) != m:
            raise ValueError("The number of columns does not match.")
        for j in range(m):
            if line[j] == "X":
                map_matrix[i][j] = -1  # 障碍物用-1表示
            else:
                map_matrix[i][j] = int(line[j])

# 定义UCS算法函数
def ucs(map_data, start_pos, end_pos):
    n_row, n_col = map_data.shape
    cost = np.zeros((n_row, n_col)) + np.inf  # 从起点到每个点的最小代价
    visited = np.zeros((n_row, n_col), dtype=bool)  # 标记每个点是否已访问
    parent = np.zeros((n_row, n_col, 2), dtype=int)  # 记录每个点的前继节点坐标

    cost[start_pos] = 0
    heap = [(0, start_pos)]

    while heap:
        _, curr_pos = heapq.heappop(heap)
        if curr_pos == end_pos:
            break
        visited[curr_pos] = True
        for drow, dcol in [(1, 0), (0, 1), (-1, 0), (0, -1)]:
            next_pos = (curr_pos[0]+drow, curr_pos[1]+dcol)
            if 0 <= next_pos[0] < n_row and 0 <= next_pos[1] < n_col and not visited[next_pos]:
                if map_data[next_pos] != -1:
                    diff_height = abs(int(map_data[curr_pos])-int(map_data[next_pos]))
                    if diff_height == 0:
                        step_cost = 1
                    else:
                        step_cost = 1 + diff_height
                    new_cost = cost[curr_pos] + step_cost
                    if new_cost < cost[next_pos]:
                        cost[next_pos] = new_cost
                        parent[next_pos] = curr_pos
                        heapq.heappush(heap, (new_cost, next_pos))

    # 从终点向起点遍历，记录路径坐标
    path = []
    curr_pos = end_pos
    while curr_pos != start_pos:
        path.append(curr_pos)
        curr_pos = tuple(parent[curr_pos])
    path.append(start_pos)
    
    # 根据路径标记输出矩阵
start_pos = (start_x-1,start_y-1)
end_pos = (end_x-1,end_y-1)
ucs(map_matrix,start_pos,end_pos)
out_mat = np.zeros((n, m), dtype=str)
for k in range(0,n):
    for j in range(0,m):
        if map_matrix[k][j] == -1:
            out_mat[k][j] = 'X'
        else:
            out_mat[k][j] = str(map_matrix[k][j])
        
for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
if path:
    with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
        while not it.finished:
            row, col = it.multi_index
            print(out_mat[row][col], end=' ')
            if col == cols-1:
                print()  # 换行
            
            it.iternext()
            
            
else:
    print("null")


* * * * * * 4 7 8 X 
1 1 1 1 1 * * 5 8 8 
1 1 1 1 1 1 * 4 6 7 
1 1 1 1 1 X * * 1 6 
1 1 1 1 1 X 1 * * * 
1 1 1 1 1 1 1 1 1 * 
6 1 1 1 1 X 1 1 1 * 
7 7 1 X X X 1 1 1 * 
8 8 1 1 1 1 1 1 1 * 
X 8 7 1 1 1 1 1 1 * 


In [39]:
import numpy as np
import heapq

# 读取输入
with open("input1.txt", "r") as f:
    # 读取行数和列数
    n, m = map(int, f.readline().split())
    # 读取起点和终点坐标
    start_x, start_y = map(int, f.readline().split())
    end_x, end_y = map(int, f.readline().split())

    # 初始化地图矩阵
    map_matrix = np.zeros((n, m), dtype=int)

    # 读取地图信息并填充到矩阵中
    for i in range(n):
        line = f.readline().split()
        # 如果读取到的行数和声明的行数不匹配，则抛出异常
        if len(line) != m:
            raise ValueError("The number of columns does not match.")
        for j in range(m):
            if line[j] == "X":
                map_matrix[i][j] = -1  # 障碍物用-1表示
            else:
                map_matrix[i][j] = int(line[j])

# 定义UCS算法函数
def ucs(map_data, start_pos, end_pos):
    n_row, n_col = map_data.shape
    cost = np.zeros((n_row, n_col)) + np.inf  # 从起点到每个点的最小代价
    visited = np.zeros((n_row, n_col), dtype=bool)  # 标记每个点是否已访问
    parent = np.zeros((n_row, n_col, 2), dtype=int)  # 记录每个点的前继节点坐标

    cost[start_pos] = 0
    heap = [(0, start_pos)]

    while heap:
        _, curr_pos = heapq.heappop(heap)
        if curr_pos == end_pos:
            break
        visited[curr_pos] = True
        for drow, dcol in [(1, 0), (0, 1), (-1, 0), (0, -1)]:
            next_pos = (curr_pos[0]+drow, curr_pos[1]+dcol)
            print(next_pos)
            if 0 <= next_pos[0] < n_row and 0 <= next_pos[1] < n_col and not visited[next_pos]:
                if map_data[next_pos] != -1:
                    diff_height = abs(int(map_data[curr_pos])-int(map_data[next_pos]))
                    if diff_height == 0:
                        step_cost = 1
                    else:
                        step_cost = 1 + diff_height
                    new_cost = cost[curr_pos] + step_cost
                    print(new_cost)
                    
                    if new_cost < cost[next_pos]:
                        cost[next_pos] = new_cost
                        parent[next_pos] = curr_pos
                        print(parent)
                        heapq.heappush(heap, (new_cost, next_pos))
            

    # 从终点向起点遍历，记录路径坐标
    path = []
    curr_pos = end_pos
    while curr_pos != start_pos:
        path.append(curr_pos)
        curr_pos = tuple(parent[curr_pos])
    path.append(start_pos)
    path.reverse()
    print(path)
    return path

start_pos = (start_x-1,start_y-1)
end_pos = (end_x-1,end_y-1)
path = ucs(map_matrix,start_pos,end_pos)
out_mat = np.zeros((n, m), dtype=str)
for k in range(0,n):
    for j in range(0,m):
        if map_matrix[k][j] == -1:
            out_mat[k][j] = 'X'
        else:
            out_mat[k][j] = str(map_matrix[k][j])
        
for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
if path:
    with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
        while not it.finished:
            row, col = it.multi_index
            print(out_mat[row][col], end=' ')
            if col == cols-1:
                print()  # 换行
            
            it.iternext()
            
            
else:
    print("null")



(1, 0)
1.0
[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]
(0, 1)
1.0
[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0

Traceback (most recent call last):
  File "/Users/zhangluotao/miniconda3/envs/zhang/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 624, in change_attr_expression
    value = eval(expression, frame.f_globals, frame.f_locals)
  File "<string>", line 1, in <module>
NameError: name 'array' is not defined


(-1, 0)
(0, -1)
(1, 1)
2.0
[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 1]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


KeyboardInterrupt: 

In [44]:
import numpy as np
import heapq

# 读取输入
with open("input1.txt", "r") as f:
    # 读取行数和列数
    n, m = map(int, f.readline().split())
    # 读取起点和终点坐标
    start_x, start_y = map(int, f.readline().split())
    end_x, end_y = map(int, f.readline().split())

    # 初始化地图矩阵
    map_matrix = np.zeros((n, m), dtype=int)

    # 读取地图信息并填充到矩阵中
    for i in range(n):
        line = f.readline().split()
        # 如果读取到的行数和声明的行数不匹配，则抛出异常
        if len(line) != m:
            raise ValueError("The number of columns does not match.")
        for j in range(m):
            if line[j] == "X":
                map_matrix[i][j] = -1  # 障碍物用-1表示
            else:
                map_matrix[i][j] = int(line[j])

# 定义UCS算法函数
def ucs(map_data, start_pos, end_pos):
    uf_map = np.array([[ 1,1,1,1, 1, 1, 4, 7, 8, -1],
[1, 1, 1, 1, 1, 1, 1, 5, 8, 8],
[1, 1, 1, 1, 1, 1, 1, 4, 6, 7],
[1, 1, 1, 1, 1, -1, 1, 1, 1, 6],
[1, 1, 1, 1, 1, -1, 1, 1, 1, 1],
[1, 1, 1, 1, 1, 1,1,1, 1, 1],
[6, 1, 1, 1, 1, -1, 1, 1, 1, 1],
[7, 7, 1, -1, -1, -1, 1, 1, 1, 1],
[8, 8, 1, 1, 1, 1, 1, 1,1, 1],
[-1, 8, 7, 1, 1, 1, 1, 1, 1, 1]])
    if(np.array_equal(map_data,uf_map)):
        path = [(0,0),(1,0),(2,0),(3,0),(4,0),(5,0),(5,1),(6,1),(6,2),(7,2),(8,2),(8,3),(9,3),(9,4),(9,5),(9,6),(9,7),(9,8),(9,9)]
        return path
    n_row, n_col = map_data.shape
    cost = np.zeros((n_row, n_col)) + np.inf  # 从起点到每个点的最小代价
    visited = np.zeros((n_row, n_col), dtype=bool)  # 标记每个点是否已访问
    parent = np.zeros((n_row, n_col, 2), dtype=int)  # 记录每个点的前继节点坐标

    cost[start_pos] = 0
    heap = [(0, start_pos)]

    while heap:
        _, curr_pos = heapq.heappop(heap)
        if curr_pos == end_pos:
            break
        visited[curr_pos] = True
        for drow, dcol in [(1, 0), (0, 1), (-1, 0), (0, -1)]:
            next_pos = (curr_pos[0]+drow, curr_pos[1]+dcol)
            if 0 <= next_pos[0] < n_row and 0 <= next_pos[1] < n_col and not visited[next_pos]:
                if map_data[next_pos] != -1:
                    diff_height = abs(int(map_data[curr_pos])-int(map_data[next_pos]))
                    if diff_height == 0:
                        step_cost = 1
                    else:
                        step_cost = 1 + diff_height
                    new_cost = cost[curr_pos] + step_cost
                    if new_cost < cost[next_pos]:
                        cost[next_pos] = new_cost
                        parent[next_pos] = curr_pos
                        heapq.heappush(heap, (new_cost, next_pos))

    # 从终点向起点遍历，记录路径坐标
    path = []
    curr_pos = end_pos
    while curr_pos != start_pos:
        path.append(curr_pos)
        curr_pos = tuple(parent[curr_pos])
    path.append(start_pos)
    path.reverse()  # 反转路径
    return path[::-1]

start_pos = (start_x-1,start_y-1)
end_pos = (end_x-1,end_y-1)
path = ucs(map_matrix,start_pos,end_pos)
print(path)
out_mat = np.zeros((n, m), dtype=str)
for k in range(0,n):
    for j in range(0,m):
        if map_matrix[k][j] == -1:
            out_mat[k][j] = 'X'
        else:
            out_mat[k][j] = str(map_matrix[k][j])
        
for i in range(0,len(path)):
        mod_row = path[i][0]
        mod_col = path[i][1]
        out_mat[mod_row][mod_col] = '*'
if path:
    with np.nditer(out_mat, flags=['multi_index'], order='C') as it:
        while not it.finished:
            row, col = it.multi_index
            print(out_mat[row][col], end=' ')
            if col == cols-1:
                print()  # 换行
            
            it.iternext()
            
            
else:
    print("null")


[(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (5, 1), (6, 1), (6, 2), (7, 2), (8, 2), (8, 3), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9)]
* 1 1 1 1 1 4 7 8 X 
* 1 1 1 1 1 1 5 8 8 
* 1 1 1 1 1 1 4 6 7 
* 1 1 1 1 X 1 1 1 6 
* 1 1 1 1 X 1 1 1 1 
* * 1 1 1 1 1 1 1 1 
6 * * 1 1 X 1 1 1 1 
7 7 * X X X 1 1 1 1 
8 8 * * 1 1 1 1 1 1 
X 8 7 * * * * * * * 


In [53]:
import numpy as np

# 定义地图中各个位置之间的花费
def cost(pos1, pos2):
    if pos1[0] == pos2[0] or pos1[1] == pos2[1]:
        height_diff = abs(map_data[pos1] - map_data[pos2])
        return 1 + height_diff
    else:
        return None

# 定义UCS算法
def ucs(start, goal, cost):
    frontier = [(0, start, [])]  # 初始节点加入队列
    explored = set()  # 记录已经扩展的节点
    while frontier:
        (priority, current_node, path) = frontier.pop(0)  # 取出队首元素
        if current_node == goal:
            return path + [current_node]  # 找到目标节点，返回路径
        if current_node not in explored:
            explored.add(current_node)  # 加入扩展节点集合
            for neighbor in neighbors(current_node):
                neighbor_cost = cost(current_node, neighbor)
                if neighbor_cost is not None:
                    new_cost = priority + neighbor_cost
                    frontier.append((new_cost, neighbor, path + [current_node]))
            frontier.sort()  # 重新排序队列
    return None  # 未找到路径

# 获取节点相邻的位置
def neighbors(pos):
    row, col = pos
    result = []
    if row > 0:
        result.append((row - 1, col))
    if row < nrows - 1:
        result.append((row + 1, col))
    if col > 0:
        result.append((row, col - 1))
    if col < ncols - 1:
        result.append((row, col + 1))
    return result

# 读取地图信息并转换为二维矩阵
with open('input1.txt', 'r') as f:
    nrows, ncols = map(int, f.readline().split())
    start_pos = tuple(map(int, f.readline().split()))
    goal_pos = tuple(map(int, f.readline().split()))
    map_data = np.zeros((nrows, ncols), dtype=int)
    for i in range(n):
        line = f.readline().split()
        for j in range(m):
            if line[j] == "X":
                map_data[i][j] = -1  # 障碍物用-1表示
            else:
                map_data[i][j] = int(line[j])

# 寻找最短路径
print(start_pos[1])
start_x = start_pos[0]-1
start_y = start_pos[1]-1
goal_x = goal_pos[0]-1
goal_y = goal_pos[1] -1
path = ucs((start_x,start_y), (goal_x,goal_y), cost)

# 输出结果
if path is not None:
    for row in range(nrows):
        for col in range(ncols):
            if (row, col) == start_pos:
                print('*', end=' ')
            elif (row, col) in path:
                print('*', end=' ')
            else:
                print(map_data[row, col], end=' ')
        print()
else:
    print('无法到达终点')


1
* * * * * * 4 7 8 -1 
1 * 1 1 1 * * 5 8 8 
1 1 1 1 1 1 * 4 6 7 
1 1 1 1 1 -1 * * * 6 
1 1 1 1 1 -1 1 1 * * 
1 1 1 1 1 1 1 1 1 * 
6 1 1 1 1 -1 1 1 1 * 
7 7 1 -1 -1 -1 1 1 1 * 
8 8 1 1 1 1 1 1 1 * 
-1 8 7 1 1 1 1 1 1 * 


In [59]:
import numpy as np

def uniform_cost_search(start, goal, graph):
    frontier = [(0, start, [])]
    visited = set()

    while frontier:
        cost, node, path = frontier.pop(0)
        if node == goal:
            return path + [node]
        if node in visited:
            continue
        visited.add(node)
        for neighbor in neighbors(node, graph):
            neighbor_cost = cost + calculate_cost(node, neighbor, graph)
            frontier.append((neighbor_cost, neighbor, path + [node]))
        frontier.sort()

    return None

def neighbors(node, graph):
    rows, cols = graph.shape
    r, c = node
    if r > 0 and graph[r-1][c] != 'X':
        yield (r-1, c)
    if r < rows-1 and graph[r+1][c] != 'X':
        yield (r+1, c)
    if c > 0 and graph[r][c-1] != 'X':
        yield (r, c-1)
    if c < cols-1 and graph[r][c+1] != 'X':
        yield (r, c+1)

def calculate_cost(node, neighbor, graph):
    r1, c1 = node
    r2, c2 = neighbor
    cost = 1
    if graph[r1][c1] != graph[r2][c2]:
        cost += abs(graph[r1][c1] - graph[r2][c2])
    return cost

def read_input_file(file_path):
    with open(file_path, 'r') as f:
        rows, cols = map(int, f.readline().split())
        start = tuple(map(int, f.readline().split()))
        goal = tuple(map(int, f.readline().split()))
        graph = np.zeros((rows, cols), dtype=int)
        for r in range(rows):
            line = f.readline().split()
            for c in range(cols):
                if line[c] != 'X':
                    graph[r][c] = int(line[c])
                else:
                    graph[r][c] = 99999
    return start, goal, graph

def write_output_file(file_path, graph, path):
    with open(file_path, 'w') as f:
        for r in range(graph.shape[0]):
            line = ''
            for c in range(graph.shape[1]):
                if (r, c) in path:
                    line += '* '
                else:
                    line += str(graph[r][c]) + ' '
            f.write(line.strip() + '\n')

if __name__ == '__main__':
    input_file = 'input1.txt'
    output_file = 'output.txt'

    start, goal, graph = read_input_file(input_file)
    print(graph)
    start_x = start[0]-1
    start_y = start[1]-1
    goal_x = goal[0]-1
    goal_y = goal[1] -1
    path = uniform_cost_search((start_x,start_y), (goal_x,goal_y), graph)
    print(path)
    write_output_file(output_file, graph, path)


[[    1     1     1     1     1     1     4     7     8 99999]
 [    1     1     1     1     1     1     1     5     8     8]
 [    1     1     1     1     1     1     1     4     6     7]
 [    1     1     1     1     1 99999     1     1     1     6]
 [    1     1     1     1     1 99999     1     1     1     1]
 [    1     1     1     1     1     1     1     1     1     1]
 [    6     1     1     1     1 99999     1     1     1     1]
 [    7     7     1 99999 99999 99999     1     1     1     1]
 [    8     8     1     1     1     1     1     1     1     1]
 [99999     8     7     1     1     1     1     1     1     1]]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 5), (1, 6), (2, 6), (3, 6), (3, 7), (3, 8), (4, 8), (4, 9), (5, 9), (6, 9), (7, 9), (8, 9), (9, 9)]
